

import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author migue
 */
public class admin_login extends javax.swing.JFrame {

    /**
     * Creates new form admin_login
     */
    public admin_login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_usuario = new javax.swing.JLabel();
        txt_usuario = new javax.swing.JTextField();
        lbl_contra = new javax.swing.JLabel();
        txt_cont = new javax.swing.JPasswordField();
        btn_ingresar = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        lbl_back3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_usuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usuario.setText("USUARIO:");
        getContentPane().add(lbl_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 90, 30));

        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 200, 30));

        lbl_contra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_contra.setForeground(new java.awt.Color(255, 255, 255));
        lbl_contra.setText("CONTRASEÑA:");
        getContentPane().add(lbl_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, -1, -1));
        getContentPane().add(txt_cont, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 200, 30));

        btn_ingresar.setText("INGRESAR");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 140, 50));

        btn_regresar.setText("REGRESAR");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 130, 50));

        lbl_back3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/3a245d83eef7a69961c7f19540e972c1.jpg"))); // NOI18N
        getContentPane().add(lbl_back3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        // TODO add your handling code here:

        try{
            ConexionMySQL Con = new ConexionMySQL();
            String u = txt_usuario.getText();
            String c = txt_cont.getText();
            Con.ConectarBasedeDatos();
            String SQL = "SELECT COUNT(id_admin) AS i FROM administrador WHERE nickname ='"+u+"'"+" AND pass = '"+c+"' ";
            
            Con.resultado = Con.sentencia.executeQuery(SQL);
            while (Con.resultado.next()){
                if (Con.resultado.getString("i").equals("1")) {
                    setVisible(false);
                    Menu menu = new Menu();
                    menu.setVisible(true);
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Usuario o contraseña invalida");
                }
            }
            Con.DesconectarBasedeDatos();
        } catch (SQLException ex){
            
        }
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        ventana2 ven = new ventana2();
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JLabel lbl_back3;
    private javax.swing.JLabel lbl_contra;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JPasswordField txt_cont;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
