/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author migue
 */
public class bienvenida extends javax.swing.JFrame {

    /**
     * Creates new form bienvenida
     */
    public bienvenida() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_bien = new javax.swing.JLabel();
        lbl_a = new javax.swing.JLabel();
        lbl_programa = new javax.swing.JLabel();
        btn_iniciar = new javax.swing.JButton();
        lbl_back14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_bien.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        lbl_bien.setForeground(new java.awt.Color(240, 240, 240));
        lbl_bien.setText("BIENVENIDO");
        getContentPane().add(lbl_bien, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        lbl_a.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        lbl_a.setForeground(new java.awt.Color(240, 240, 240));
        lbl_a.setText("A");
        getContentPane().add(lbl_a, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 70, 90));

        lbl_programa.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        lbl_programa.setForeground(new java.awt.Color(240, 240, 240));
        lbl_programa.setText("Pro&Task");
        getContentPane().add(lbl_programa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, -1, -1));

        btn_iniciar.setText("INICIAR");
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 140, 40));

        lbl_back14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/3a245d83eef7a69961c7f19540e972c1.jpg"))); // NOI18N
        getContentPane().add(lbl_back14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 510, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed
        // TODO add your handling code here:
        Inicio ini= new Inicio();
        ini.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_iniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bienvenida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bienvenida().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JLabel lbl_a;
    private javax.swing.JLabel lbl_back14;
    private javax.swing.JLabel lbl_bien;
    private javax.swing.JLabel lbl_programa;
    // End of variables declaration//GEN-END:variables
}
