
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author migue
 */
public class login_Admin extends javax.swing.JFrame {

    Connection con = null;
    Statement stmt = null;
    public login_Admin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_nombre = new javax.swing.JLabel();
        LBL_APELLIDO = new javax.swing.JLabel();
        LBL_NICK = new javax.swing.JLabel();
        LBL_CONTRASEÑA = new javax.swing.JLabel();
        TXT_CONTRASEÑA = new javax.swing.JPasswordField();
        BTN_ACEPTAR = new javax.swing.JButton();
        TXT_NOMBRE = new javax.swing.JTextField();
        TXT_APELLIDO = new javax.swing.JTextField();
        TXT_NICKNAME = new javax.swing.JTextField();
        BTN_REGRESO = new javax.swing.JButton();
        lbl_id = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        lbl_back2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_nombre.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombre.setText("NOMBRE: ");
        getContentPane().add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        LBL_APELLIDO.setForeground(new java.awt.Color(255, 255, 255));
        LBL_APELLIDO.setText("APELLIDO:");
        getContentPane().add(LBL_APELLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        LBL_NICK.setForeground(new java.awt.Color(255, 255, 255));
        LBL_NICK.setText("NICKNAME:");
        getContentPane().add(LBL_NICK, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 80, 20));

        LBL_CONTRASEÑA.setForeground(new java.awt.Color(255, 255, 255));
        LBL_CONTRASEÑA.setText("CONTRASEÑA");
        getContentPane().add(LBL_CONTRASEÑA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 110, 20));
        getContentPane().add(TXT_CONTRASEÑA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 260, 30));

        BTN_ACEPTAR.setText("ACEPTAR");
        BTN_ACEPTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ACEPTARActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_ACEPTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 160, 40));

        TXT_NOMBRE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_NOMBREActionPerformed(evt);
            }
        });
        TXT_NOMBRE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_NOMBREKeyTyped(evt);
            }
        });
        getContentPane().add(TXT_NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 250, 30));

        TXT_APELLIDO.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TXT_APELLIDOKeyTyped(evt);
            }
        });
        getContentPane().add(TXT_APELLIDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 260, 30));
        getContentPane().add(TXT_NICKNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 260, 30));

        BTN_REGRESO.setText("REGRESAR ALA PAG ANTERIOR");
        BTN_REGRESO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_REGRESOActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_REGRESO, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 220, 40));

        lbl_id.setForeground(new java.awt.Color(255, 255, 255));
        lbl_id.setText("ID:");
        getContentPane().add(lbl_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        txt_id.setEditable(false);
        txt_id.setBackground(new java.awt.Color(153, 153, 153));
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 80, -1));

        lbl_back2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/3a245d83eef7a69961c7f19540e972c1.jpg"))); // NOI18N
        getContentPane().add(lbl_back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_ACEPTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ACEPTARActionPerformed
        // TODO add your handling code here:
        String cadena2,cadena3,cadena4,cadena5;
        
        cadena2 = TXT_NOMBRE.getText();
        cadena3 = TXT_APELLIDO.getText();
        cadena4 = TXT_NICKNAME.getText();
        cadena5 = TXT_CONTRASEÑA.getText().toString();
        
         if (TXT_NOMBRE.getText().equals("") || (TXT_APELLIDO.getText().equals("")) || (TXT_NICKNAME.getText().equals(""))
           || (TXT_CONTRASEÑA.getText().equals(""))) {
             javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            TXT_NOMBRE.requestFocus();
        }
                 else {
        try {
           
            String url = "jdbc:mysql://localhost:3306/proyecto";
            String usuario = "root";
            String contraseña = "12345";
            
             Class.forName("com.mysql.jdbc.Driver").newInstance(); 
             con = DriverManager.getConnection(url,usuario,contraseña); 
             if ( con != null ) 
                    System.out.println("Se ha establecido una conexion a la base de datos " + url ); 
  
                  stmt = con.createStatement(); 
                   stmt.executeUpdate("INSERT INTO administrador VALUES('" + 0 + "','"+cadena2+"','"+cadena3+"','"+cadena4+"','"+cadena5+"')");
                  System.out.println("Los valores han sido agregados a la base de datos ");
                 
                   
        } catch (InstantiationException | IllegalAccessException | ClassNotFoundException | SQLException ex) {
           Logger.getLogger(login_Admin.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        finally {
            if (con != null) {
                try {
                    con.close();
                    stmt.close();
                } catch ( SQLException e ) { 
                         System.out.println( e.getMessage());
                }
            }
        }
         javax.swing.JOptionPane.showMessageDialog(this,"Registro exitoso! \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        this.TXT_NOMBRE.setText("");
        this.TXT_APELLIDO.setText("");
        this.TXT_NICKNAME.setText("");
        this.TXT_CONTRASEÑA.setText("");  
        
       
    }//GEN-LAST:event_BTN_ACEPTARActionPerformed

    private void TXT_NOMBREActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_NOMBREActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TXT_NOMBREActionPerformed

    private void TXT_NOMBREKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_NOMBREKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume(); {
            
        }
    }//GEN-LAST:event_TXT_NOMBREKeyTyped

    private void TXT_APELLIDOKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TXT_APELLIDOKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if ((c<'a' || c>'z') && (c<'A' || c>'Z') && (c<' ' || c>' ')) evt.consume(); {
            
        }

    }//GEN-LAST:event_TXT_APELLIDOKeyTyped

    private void BTN_REGRESOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_REGRESOActionPerformed
        // TODO add your handling code here:
        ventana2 ini2 = new ventana2();
        ini2.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BTN_REGRESOActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_ACEPTAR;
    private javax.swing.JButton BTN_REGRESO;
    private javax.swing.JLabel LBL_APELLIDO;
    private javax.swing.JLabel LBL_CONTRASEÑA;
    private javax.swing.JLabel LBL_NICK;
    private javax.swing.JTextField TXT_APELLIDO;
    private javax.swing.JPasswordField TXT_CONTRASEÑA;
    private javax.swing.JTextField TXT_NICKNAME;
    private javax.swing.JTextField TXT_NOMBRE;
    private javax.swing.JLabel lbl_back2;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
