/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author migue
 */
public class MenuParticipantes extends javax.swing.JFrame {

    /**
     * Creates new form MenuParticipantes
     */
    public MenuParticipantes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_vertareas = new javax.swing.JButton();
        btn_cerrarS = new javax.swing.JButton();
        btn_verproyecto = new javax.swing.JButton();
        btn_progreso = new javax.swing.JButton();
        btn_verProgreso = new javax.swing.JButton();
        lbl_back12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_vertareas.setText("VER TAREAS");
        btn_vertareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vertareasActionPerformed(evt);
            }
        });
        getContentPane().add(btn_vertareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 180, 40));

        btn_cerrarS.setText("CERRAR SESION");
        btn_cerrarS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarSActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cerrarS, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 160, 50));

        btn_verproyecto.setText("VER PROYECTO");
        btn_verproyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verproyectoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_verproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 180, 40));

        btn_progreso.setText("PROGRESO TAREA");
        btn_progreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_progresoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_progreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 180, 40));

        btn_verProgreso.setText("VER PROGRESO DE LAS TAREAS");
        btn_verProgreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verProgresoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_verProgreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 240, 40));

        lbl_back12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/3a245d83eef7a69961c7f19540e972c1.jpg"))); // NOI18N
        getContentPane().add(lbl_back12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_vertareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vertareasActionPerformed
        // TODO add your handling code here:
        ver_tareasp ver= new ver_tareasp();
        ver.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_vertareasActionPerformed

    private void btn_cerrarSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarSActionPerformed
        // TODO add your handling code here:
        ventana3 ven= new ventana3();
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_cerrarSActionPerformed

    private void btn_verproyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verproyectoActionPerformed
        // TODO add your handling code here:
        ver_proyectop ve1= new ver_proyectop();
        ve1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_verproyectoActionPerformed

    private void btn_progresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_progresoActionPerformed
        // TODO add your handling code here:
        ProgresoTarea pro = new ProgresoTarea();
        pro.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_progresoActionPerformed

    private void btn_verProgresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verProgresoActionPerformed
        // TODO add your handling code here:
        ver_progreso ver= new ver_progreso();
        ver.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_verProgresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuParticipantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuParticipantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuParticipantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuParticipantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuParticipantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrarS;
    private javax.swing.JButton btn_progreso;
    private javax.swing.JButton btn_verProgreso;
    private javax.swing.JButton btn_verproyecto;
    private javax.swing.JButton btn_vertareas;
    private javax.swing.JLabel lbl_back12;
    // End of variables declaration//GEN-END:variables
}
