
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author migue
 */
public class participante_login extends javax.swing.JFrame {

    /**
     * Creates new form participante_login
     */
    public participante_login() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_correoP = new javax.swing.JLabel();
        txt_correop = new javax.swing.JTextField();
        lbl_contraP = new javax.swing.JLabel();
        txt_passP = new javax.swing.JPasswordField();
        btn_ingresarP = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        lbl_back9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_correoP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_correoP.setForeground(new java.awt.Color(240, 240, 240));
        lbl_correoP.setText("USUARIO:");
        getContentPane().add(lbl_correoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));
        getContentPane().add(txt_correop, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 220, 30));

        lbl_contraP.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_contraP.setForeground(new java.awt.Color(240, 240, 240));
        lbl_contraP.setText("CONTRASEÑA:");
        getContentPane().add(lbl_contraP, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));
        getContentPane().add(txt_passP, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 230, 30));

        btn_ingresarP.setText("INGRESAR");
        btn_ingresarP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarPActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ingresarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 140, 50));

        btn_regresar.setText("REGRESAR");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 120, 50));

        lbl_back9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/3a245d83eef7a69961c7f19540e972c1.jpg"))); // NOI18N
        getContentPane().add(lbl_back9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        ventana3 ven = new ventana3();
        ven.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btn_ingresarPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarPActionPerformed
        // TODO add your handling code here:
                try{
            ConexionMySQL Con = new ConexionMySQL();
            String u = txt_correop.getText();
            String c = txt_passP.getText();
            Con.ConectarBasedeDatos();
            String SQL = "SELECT COUNT(id_participantes) AS i FROM participantes WHERE nick ='"+u+"'"+" AND pass = '"+c+"' ";
            
            Con.resultado = Con.sentencia.executeQuery(SQL);
            while (Con.resultado.next()){
                if (Con.resultado.getString("i").equals("1")) {
                    setVisible(false);
                    MenuParticipantes menu = new MenuParticipantes();
                    menu.setVisible(true);
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Usuario o contraseña invalida");
                }
            }
            Con.DesconectarBasedeDatos();
        } catch (SQLException ex){
            
        }
    }//GEN-LAST:event_btn_ingresarPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(participante_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(participante_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(participante_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(participante_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new participante_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ingresarP;
    private javax.swing.JButton btn_regresar;
    private javax.swing.JLabel lbl_back9;
    private javax.swing.JLabel lbl_contraP;
    private javax.swing.JLabel lbl_correoP;
    private javax.swing.JTextField txt_correop;
    private javax.swing.JPasswordField txt_passP;
    // End of variables declaration//GEN-END:variables
}
