
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;







/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author migue
 */
public class registrar_proyecto extends javax.swing.JFrame {
        conexionsql2 con = new conexionsql2();
        Connection cn = con.conectar();
    
        public registrar_proyecto() {
        initComponents();
        this.setLocationRelativeTo(null);
        
       
        this.ComboPrioridad.removeAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_ID = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        lbl_nombrePr = new javax.swing.JLabel();
        txt_nombrePr = new javax.swing.JTextField();
        lbl_objetivo = new javax.swing.JLabel();
        lbl_fechaI = new javax.swing.JLabel();
        lbl_fechaT = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JButton();
        btn_regresar = new javax.swing.JButton();
        fechaInicio = new com.toedter.calendar.JDateChooser();
        fechatermino = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_objetivo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        ComboPrioridad = new javax.swing.JComboBox<>();
        lbl_back8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_ID.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ID.setText("ID:");
        lbl_ID.setToolTipText("");
        getContentPane().add(lbl_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txt_id.setEditable(false);
        txt_id.setBackground(new java.awt.Color(204, 204, 204));
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 20, -1));

        lbl_nombrePr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_nombrePr.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombrePr.setText("Nombre del Proyecto:");
        getContentPane().add(lbl_nombrePr, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));
        getContentPane().add(txt_nombrePr, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 180, -1));

        lbl_objetivo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_objetivo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_objetivo.setText("Objetivo:");
        getContentPane().add(lbl_objetivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, -1, -1));

        lbl_fechaI.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_fechaI.setForeground(new java.awt.Color(240, 240, 240));
        lbl_fechaI.setText("Fecha de Inicio:");
        getContentPane().add(lbl_fechaI, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        lbl_fechaT.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_fechaT.setForeground(new java.awt.Color(240, 240, 240));
        lbl_fechaT.setText("Fecha final:");
        getContentPane().add(lbl_fechaT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        btn_registrar.setText("REGISTRAR");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        btn_regresar.setText("REGRESAR AL MENU");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, -1, -1));

        fechaInicio.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(fechaInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 170, -1));

        fechatermino.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(fechatermino, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 170, -1));

        txt_objetivo.setColumns(20);
        txt_objetivo.setRows(5);
        jScrollPane1.setViewportView(txt_objetivo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 270, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Prioridad:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 80, -1));

        ComboPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboPrioridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboPrioridadActionPerformed(evt);
            }
        });
        getContentPane().add(ComboPrioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 170, -1));

        lbl_back8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/3a245d83eef7a69961c7f19540e972c1.jpg"))); // NOI18N
        getContentPane().add(lbl_back8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        Menu men = new Menu();
        men.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        String nombreProyecto = txt_nombrePr.getText();
        String objetivo = txt_objetivo.getText();
        String fechai = ((JTextField) fechaInicio.getDateEditor().getUiComponent()).getText();
        String fechat = ((JTextField) fechatermino.getDateEditor().getUiComponent()).getText();
        String prioridad = ComboPrioridad.getSelectedItem().toString();

        regisProyecto r = new regisProyecto(nombreProyecto, objetivo, Date.valueOf(fechai), Date.valueOf(fechat), prioridad);

        try {
            PreparedStatement ps = cn.prepareStatement("INSERT INTO registro (nombreProyecto, objetivo, fechaInicio, fechatermino, Prioridad) VALUES (?,?,?,?,?)");
            ps.setString(1, nombreProyecto);
            ps.setString(2, objetivo);
            ps.setDate(3, r.getFechaInicio());
            ps.setDate(4, r.getFechatermino());
            ps.setString(5, prioridad);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "DATOS GUARDADOS CORRECTAMENTE");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "NO SE PUEDE GUARDAR DATOS");
        }
     
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void ComboPrioridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboPrioridadActionPerformed
        // TODO add your handling code here:
        
        ComboPrioridad.addItem("Alta");
        ComboPrioridad.addItem("Media");
        ComboPrioridad.addItem("Baja");
        
        
    }//GEN-LAST:event_ComboPrioridadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrar_proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrar_proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrar_proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrar_proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new registrar_proyecto().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboPrioridad;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JButton btn_regresar;
    private com.toedter.calendar.JDateChooser fechaInicio;
    private com.toedter.calendar.JDateChooser fechatermino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JLabel lbl_back8;
    private javax.swing.JLabel lbl_fechaI;
    private javax.swing.JLabel lbl_fechaT;
    private javax.swing.JLabel lbl_nombrePr;
    private javax.swing.JLabel lbl_objetivo;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nombrePr;
    private javax.swing.JTextArea txt_objetivo;
    // End of variables declaration//GEN-END:variables
}
