
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author migue
 */
public class registro extends javax.swing.JFrame {

     Connection con = null;
    Statement stmt = null;
    
    public registro() {
        initComponents();
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_idp = new javax.swing.JLabel();
        txt_idp = new javax.swing.JTextField();
        lbl_nombrep = new javax.swing.JLabel();
        txt_nombrep = new javax.swing.JTextField();
        lbl_apellidop = new javax.swing.JLabel();
        txt_apellidop = new javax.swing.JTextField();
        lbl_nicknamep = new javax.swing.JLabel();
        txt_nickp = new javax.swing.JTextField();
        labl_passw = new javax.swing.JLabel();
        btn_aceptarp = new javax.swing.JButton();
        txt_contrap = new javax.swing.JPasswordField();
        btn_regreso = new javax.swing.JButton();
        lbl_back5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_idp.setForeground(new java.awt.Color(255, 255, 255));
        lbl_idp.setText("ID:");
        getContentPane().add(lbl_idp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        txt_idp.setEditable(false);
        txt_idp.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(txt_idp, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 70, -1));

        lbl_nombrep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_nombrep.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nombrep.setText("NOMBRE:");
        getContentPane().add(lbl_nombrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));
        getContentPane().add(txt_nombrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 210, 30));

        lbl_apellidop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_apellidop.setForeground(new java.awt.Color(255, 255, 255));
        lbl_apellidop.setText("APELLIDO:");
        getContentPane().add(lbl_apellidop, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, -1, -1));
        getContentPane().add(txt_apellidop, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 210, 30));

        lbl_nicknamep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_nicknamep.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nicknamep.setText("NICKNAME:");
        getContentPane().add(lbl_nicknamep, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 90, 20));
        getContentPane().add(txt_nickp, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 210, 30));

        labl_passw.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labl_passw.setForeground(new java.awt.Color(255, 255, 255));
        labl_passw.setText("CONTRASEÑA:");
        getContentPane().add(labl_passw, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 110, 20));

        btn_aceptarp.setText("ACEPTAR");
        btn_aceptarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_aceptarpActionPerformed(evt);
            }
        });
        getContentPane().add(btn_aceptarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 130, 40));
        getContentPane().add(txt_contrap, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 210, 30));

        btn_regreso.setText("REGRESAR");
        btn_regreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 120, 40));

        lbl_back5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbl_back5.setForeground(new java.awt.Color(255, 255, 255));
        lbl_back5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/3a245d83eef7a69961c7f19540e972c1.jpg"))); // NOI18N
        getContentPane().add(lbl_back5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_aceptarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_aceptarpActionPerformed
        // TODO add your handling code here:
        String cadena2,cadena3,cadena4,cadena5;
        
        cadena2 = txt_nombrep.getText();
        cadena3 = txt_apellidop.getText();
        cadena4 = txt_nickp.getText();
        cadena5 = txt_contrap.getText().toString();
        
        if (txt_nombrep.getText().equals("") || (txt_apellidop.getText().equals("")) || (txt_nickp.getText().equals(""))
           || (txt_contrap.getText().equals(""))) {
             javax.swing.JOptionPane.showMessageDialog(this,"Debe llenar todos los campos \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            txt_nombrep.requestFocus();
        }
             else {
        try {
           
            String url = "jdbc:mysql://localhost:3306/proyecto";
            String usuario = "root";
            String contraseña = "12345";
            
             Class.forName("com.mysql.jdbc.Driver").newInstance(); 
             con = DriverManager.getConnection(url,usuario,contraseña); 
             if ( con != null ) 
                    System.out.println("Se ha establecido una conexion a la base de datos " + url ); 
  
                  stmt = con.createStatement(); 
                   stmt.executeUpdate("INSERT INTO participantes VALUES('" + 0 + "','"+cadena2+"','"+cadena3+"','"+cadena4+"','"+cadena5+"')");
                  System.out.println("Los valores han sido agregados a la base de datos ");
                 
                   
        } catch (InstantiationException | IllegalAccessException | ClassNotFoundException | SQLException ex) {
           Logger.getLogger(registro.class.getName()).log(Level.SEVERE, null, ex);
       }
        
        finally {
            if (con != null) {
                try {
                    con.close();
                    stmt.close();
                } catch ( SQLException e ) { 
                         System.out.println( e.getMessage());
                }
            }
        }
         javax.swing.JOptionPane.showMessageDialog(this,"Registro exitoso! \n","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        this.txt_nombrep.setText("");
        this.txt_apellidop.setText("");
        this.txt_nickp.setText("");
        this.txt_contrap.setText("");
        
        
    }//GEN-LAST:event_btn_aceptarpActionPerformed

    private void btn_regresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresoActionPerformed
        // TODO add your handling code here:
        ventana3 ve= new ventana3();
        ve.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_regresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_aceptarp;
    private javax.swing.JButton btn_regreso;
    private javax.swing.JLabel labl_passw;
    private javax.swing.JLabel lbl_apellidop;
    private javax.swing.JLabel lbl_back5;
    private javax.swing.JLabel lbl_idp;
    private javax.swing.JLabel lbl_nicknamep;
    private javax.swing.JLabel lbl_nombrep;
    private javax.swing.JTextField txt_apellidop;
    private javax.swing.JPasswordField txt_contrap;
    private javax.swing.JTextField txt_idp;
    private javax.swing.JTextField txt_nickp;
    private javax.swing.JTextField txt_nombrep;
    // End of variables declaration//GEN-END:variables
}
