/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author migue
 */
public class ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form ventana2
     */
    public ventana2() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_registr = new javax.swing.JButton();
        btn_inicioSe = new javax.swing.JButton();
        btn_regresa = new javax.swing.JButton();
        lbl_back2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_registr.setText("REGISTRAR");
        btn_registr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registr, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 150, 60));

        btn_inicioSe.setText("INICIAR SESION");
        btn_inicioSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicioSeActionPerformed(evt);
            }
        });
        getContentPane().add(btn_inicioSe, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 150, 60));

        btn_regresa.setText("REGRESAR");
        btn_regresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 110, 40));

        lbl_back2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/3a245d83eef7a69961c7f19540e972c1.jpg"))); // NOI18N
        getContentPane().add(lbl_back2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrActionPerformed
        // TODO add your handling code here:
        login_Admin log1 = new login_Admin();
        log1.setVisible(true);
        
        this.setVisible(false);
        
    }//GEN-LAST:event_btn_registrActionPerformed

    private void btn_inicioSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicioSeActionPerformed
        // TODO add your handling code here:
        
        admin_login ad1= new admin_login();
        ad1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_inicioSeActionPerformed

    private void btn_regresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresaActionPerformed
        // TODO add your handling code here:
        Inicio ini = new Inicio();
        ini.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_regresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inicioSe;
    private javax.swing.JButton btn_registr;
    private javax.swing.JButton btn_regresa;
    private javax.swing.JLabel lbl_back2;
    // End of variables declaration//GEN-END:variables
}
