import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public class ver_proyectop extends javax.swing.JFrame {

    Connection con = null;
        Statement stmt = null;
        String titulos[] = {"id_proyecto", "nombreProyecto", "Objetivo", "fechaInicio", "fechatermino", "Prioridad"};
        String fila[] = new String [6];
        DefaultTableModel modelo;
        
    public ver_proyectop() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        
        this.setTitle("consulta de proyectos");
        this.setLocation(335,200);
        this.setResizable(false);
        
        try {
            
            String url = "jdbc:mysql://localhost:3306/proyecto";
            String usuario = "root";
            String contraseña = "12345";  
            
               Class.forName("com.mysql.jdbc.Driver").newInstance();
               con = DriverManager.getConnection(url,usuario,contraseña);
               if (con!= null)
                   System.out.println("Se ha establecido una conexion a la base de datos"+"\n"+url);
               
               stmt = con.createStatement();
               ResultSet re = stmt.executeQuery("select* from registro");
               
               modelo = new DefaultTableModel(null,titulos);
            
               while(re.next()) {
                   
                   fila[0] = re.getString("id_proyecto");
                   fila[1] = re.getString("nombreProyecto");
                   fila[2] = re.getString("objetivo");
                   fila[3] = re.getString("fechaInicio");
                   fila[4] = re.getString("fechatermino");
                   fila[5] = re.getString("prioridad");

                   
                   modelo.addRow(fila);     
               }
               
               tabla_proyectop.setModel(modelo);
                TableColumn ci = tabla_proyectop.getColumn("id_proyecto");
                ci.setMaxWidth(45);
                TableColumn cn = tabla_proyectop.getColumn("nombreProyecto");
                cn.setMaxWidth(165);
                TableColumn co = tabla_proyectop.getColumn("objetivo");
                co.setMaxWidth(160);
                TableColumn cfe = tabla_proyectop.getColumn("fechaInicio");
                cfe.setMaxWidth(72);
                TableColumn cte = tabla_proyectop.getColumn("fechatermino");
                cte.setMaxWidth(72);
                TableColumn cp = tabla_proyectop.getColumn("Prioridad");
                cp.setMaxWidth(72);


               
        }
        catch (Exception e) {
            
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_regresar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_proyectop = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_regresar.setText("REGRESAR");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 150, 50));

        tabla_proyectop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_proyectop);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
        // TODO add your handling code here:
        MenuParticipantes Mpa= new MenuParticipantes();
        Mpa.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ver_proyectop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ver_proyectop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ver_proyectop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ver_proyectop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ver_proyectop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_regresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_proyectop;
    // End of variables declaration//GEN-END:variables
}
